/* --- AUTH --- */
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAILED = "RESET_FAILED";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

/* --- DATA --- */
// years
export const PROCESSING_YEARS = "PROCESSING_YEARS";
export const CREATE_YEAR = "CREATE_YEAR";
export const FETCH_YEARS = "FETCH_YEARS";
export const EDIT_YEAR = "EDIT_YEAR";
export const UPDATE_YEAR = "UPDATE_YEAR";
export const DELETE_YEAR = "DELETE_YEAR";

// terms
export const PROCESSING_TERMS = "PROCESSING_TERMS";
export const NEW_TERM = "NEW_TERM";
export const CREATE_TERM = "CREATE_TERM";
export const FETCH_TERMS = "FETCH_TERMS";
export const EDIT_TERM = "EDIT_TERM";
export const UPDATE_TERM = "UPDATE_TERM";
export const DELETE_TERM = "DELETE_TERM";

// courses
export const PROCESSING_COURSES = "PROCESSING_COURSES";
export const NEW_COURSE = "NEW_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";
export const FETCH_COURSES = "FETCH_COURSES";
export const EDIT_COURSE = "EDIT_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";

// classes
export const PROCESSING_CLASSES = "PROCESSING_CLASSES";
export const NEW_CLASS = "NEW_CLASS";
export const CREATE_CLASS = "CREATE_CLASS";
export const FETCH_CLASSES_FOR_DASH = "FETCH_CLASSES_FOR_DASH";
export const FETCH_CLASSES_BY_TERM = "FETCH_CLASSES_BY_TERM";
export const FETCH_CLASSES_BY_COURSE = "FETCH_CLASSES_BY_COURSE";
export const EDIT_CLASS = "EDIT_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";

// assessments
export const PROCESSING_ASSESSMENTS = "PROCESSING_ASSESSMENTS";
export const NEW_ASSESSMENT = "NEW_ASSESSMENT";
export const CREATE_ASSESSMENT = "CREATE_ASSESSMENT";
export const FETCH_ASSESSMENTS = "FETCH_ASSESSMENTS";
export const FETCH_PAST_ASSESSMENTS = "FETCH_PAST_ASSESSMENTS";
export const EDIT_ASSESSMENT = "EDIT_ASSESSMENT";
export const UPDATE_ASSESSMENT = "UPDATE_ASSESSMENT";
export const DELETE_ASSESSMENT = "DELETE_ASSESSMENT";

// tasks
export const PROCESSING_TASKS = "PROCESSING_TERMS";
export const NEW_TASK = "NEW_TASK";
export const CREATE_TASK = "CREATE_TASK";
export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_PAST_TASKS = "FETCH_PAST_TASKS";
export const EDIT_TASK = "EDIT_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";

// user
export const PROCESSING_SETTINGS = "PROCESSING_SETTINGS";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";

export const EDIT_PASSWORD = "EDIT_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const EDIT_PREFERENCES = "EDIT_PREFERENCES";
export const UPDATE_PREFERENCES = "UPDATE_PREFERENCES";

// bugs
export const PROCESSING_BUGS = "PROCESSING_BUGS";
export const CREATE_BUG = "CREATE_BUG";
export const FETCH_BUGS = "FETCH_BUGS";
export const EDIT_BUG = "EDIT_BUG";
export const UPDATE_BUG = "UPDATE_BUG";
export const DELETE_BUG = "DELETE_BUG";

// feedback
export const PROCESSING_FEEDBACK = "PROCESSING_FEEDBACK";
export const CREATE_FEEDBACK = "CREATE_FEEDBACK";
export const FETCH_FEEDBACK = "FETCH_FEEDBACK";
export const EDIT_FEEDBACK = "EDIT_FEEDBACK";
export const UPDATE_FEEDBACK = "UPDATE_FEEDBACK";
export const DELETE_FEEDBACK = "DELETE_FEEDBACK";

// notifications
export const PROCESSING_NOTIFICATIONS = "PROCESSING_NOTIFCATIONS";

/* --- ROOT --- */
export const PROCESSING_FORM = "PROCESSING_FORM";

export const POST_INVITE = "POST_INVITE";
export const INVITE_ERROR = "INVITE_ERROR";

export const POST_CONTACT = "POST_CONTACT";
export const CONTACT_ERROR = "CONTACT_ERROR";

/* --- TEAM --- */
/* AUTH */
export const FORM_POSTED = "FORM_POSTED";
export const FORM_FAILED = "FORM_FAILED";
