/* AUTH */
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

/* DATA */

// dashboard 
export const LOADING_DASHBOARD = "LOADING_DASHBOARD";
export const FETCH_DASH_ITEMS = "FETCH_DASH_ITEMS";

// years
export const LOADING_YEARS = "LOADING_YEARS";
export const FETCH_YEARS = "FETCH_YEARS";
export const EDIT_YEAR = "EDIT_YEAR";
export const NEW_YEAR = "NEW_YEAR";
export const CREATE_YEAR = "CREATE_YEAR";
export const UPDATE_YEAR = "UPDATE_YEAR";
export const DELETE_YEAR = "DELETE_YEAR";

// terms
export const LOADING_TERMS = "LOADING_TERMS";
export const FETCH_TERMS = "FETCH_TERMS";
export const EDIT_TERM = "EDIT_TERM";
export const NEW_TERM = "NEW_TERM";
export const CREATE_TERM = "CREATE_TERM";
export const UPDATE_TERM = "UPDATE_TERM";
export const DELETE_TERM = "DELETE_TERM";

// courses
export const LOADING_COURSES = "LOADING_COURSES";
export const FETCH_COURSES = "FETCH_COURSES";
export const EDIT_COURSE = "EDIT_COURSE";
export const NEW_COURSE = "NEW_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";

// modules
export const LOADING_MODULES = "LOADING_MODULES";
export const FETCH_MODULES = "FETCH_MODULES";
export const EDIT_MODULE = "EDIT_MODULE";
export const NEW_MODULE = "NEW_MODULE";
export const CREATE_MODULE = "CREATE_MODULE";
export const UPDATE_MODULE = "UPDATE_MODULE";
export const DELETE_MODULE = "DELETE_MODULE";

// classes
export const LOADING_CLASSES = "LOADING_CLASSES";
export const FETCH_CLASSES = "FETCH_CLASSES";
export const EDIT_CLASS = "EDIT_CLASS";
export const NEW_CLASS = "NEW_CLASS";
export const CREATE_CLASS = "CREATE_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";

// assessments
export const LOADING_ASSESSMENTS = "LOADING_ASSESSMENTS";
export const FETCH_ASSESSMENTS = "FETCH_ASSESSMENTS";
export const FETCH_PAST_ASSESSMENTS = "FETCH_PAST_ASSESSMENTS";
export const EDIT_ASSESSMENT = "EDIT_ASSESSMENT";
export const NEW_ASSESSMENT = "NEW_ASSESSMENT";
export const CREATE_ASSESSMENT = "CREATE_ASSESSMENT";
export const UPDATE_ASSESSMENT = "UPDATE_ASSESSMENT";
export const DELETE_ASSESSMENT = "DELETE_ASSESSMENT";

// tasks
export const LOADING_TASKS = "LOADING_TERMS";
export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_PAST_TASKS = "FETCH_PAST_TASKS";
export const EDIT_TASK = "EDIT_TASK";
export const NEW_TASK = "NEW_TASK";
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";

// settings
export const FETCH_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const FETCH_PASSWORD = "GET_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const FETCH_PREFERENCES = "GET_PREFERENCES";
export const UPDATE_PREFERENCES = "UPDATE_PREFERENCES";

export const LOADING_INTEGRATIONS = "LOADING_INTEGRATIONS";
export const FETCH_INTEGRATIONS = "GET_INTEGRATIONS";
export const EDIT_INTEGRATION = "EDIT_INTEGRATION";
export const NEW_INTEGRATION = "NEW_INTEGRATION";
export const CREATE_INTEGRATION = "CREATE_INTEGRATION";
export const UPDATE_INTEGRATION = "UPDATE_INTEGRATION";
export const DELETE_INTEGRATION = "DELETE_INTEGRATION";

/* FUNCTIONS */

// counter in dashboard
export const COUNT_DATA = "COUNT_DATA";

/* VIEWS */

// nav
export const LOADING_VIEW = "LOADING_VIEW"
export const RENDER_DASHBOARD = "RENDER_DASHBOARD";
export const RENDER_CALENDAR = "RENDER_CALENDAR";
export const RENDER_ACADEMICS = "RENDER_ACADEMICS";
export const RENDER_TASKS = "RENDER_TASKS"; 
export const RENDER_ASSESSMENTS = "RENDER_ASSESSMENTS";
export const RENDER_SEARCH = "RENDER_SEARCH";
export const RENDER_SETTINGS = "RENDER_SETTINGS";
export const RENDER_HELP = "RENDER_HELP";

// settings
export const LOADING_SETTINGS = "LOADING_SETTINGS";
export const RENDER_PROFILE = "RENDER_PROFILE";
export const RENDER_PASSWORD = "RENDER_PASSWORD";
export const RENDER_PREFERENCES = "RENDER_PREFERENCES";
export const RENDER_INTEGRATIONS = "RENDER_INTEGRATIONS";