/* --- AUTH --- */
export const USER_REQUESTED = "USER_REQUESTED";
export const USER_LOADED = "USER_LOADED";
export const USER_DELETED = "USER_DELETED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED";
export const PASSWORD_RESET_REQUEST_FAILED = "PASSWORD_RESET_REQUEST_FAILED";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_FAILED";

export const EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_RESENT_FAILED = "EMAIL_VERIFICATION_RESENT_FAILED";
export const EMAIL_VERIFICATION_RESENT_SUCCESS = "EMAIL_VERIFICATION_RESENT_SUCCESS";

export const ERRORS_RETURNED = "ERRORS_RETURNED";
export const ERRORS_LOGGED = "ERRORS_LOGGED";
export const ERRORS_CLEARED = "ERRORS_CLEARED";

/* --- INTERFACE --- */


/* --- DATA --- */
// years
export const YEARS_REQUESTED = "YEARS_REQUESTED";
export const YEARS_ERROR = "YEARS_ERROR";
export const YEAR_CREATED = "YEAR_CREATED";
export const YEARS_FETCHED = "YEARS_FETCHED";
export const YEAR_RETURNED = "YEAR_RETURNED";
export const YEAR_UPDATED = "YEAR_UPDATED";
export const YEAR_DELETED = "YEAR_DELETED";

// terms
export const TERMS_REQUESTED = "TERMS_REQUESTED";
export const TERMS_ERROR = "TERMS_ERROR";
export const TERM_CREATED = "TERM_CREATED";
export const TERMS_FETCHED = "TERMS_FETCHED";
export const TERM_RETURNED = "TERM_RETURNED";
export const TERM_UPDATED = "TERM_UPDATED";
export const TERM_DELETED = "TERM_DELETED";

// courses
export const COURSES_REQUESTED = "COURSES_REQUESTED";
export const COURSES_ERROR = "COURSES_ERROR";
export const COURSE_CREATED = "COURSE_CREATED";
export const COURSES_FETCHED = "COURSES_FETCHED";
export const COURSE_RETURNED = "COURSE_RETURNED";
export const COURSE_UPDATED = "COURSE_UPDATED";
export const COURSE_DELETED = "COURSE_DELETED";

// classes
export const CLASSES_REQUESTED = "CLASSES_REQUESTED";
export const CLASSES_ERROR = "CLASSES_ERROR";
export const CLASS_CREATED = "CLASS_CREATED";
export const CLASSES_FETCHED = "CLASSES_FETCHED";
export const CLASS_RETURNED = "CLASS_RETURNED";
export const CLASS_UPDATED = "CLASS_UPDATED";
export const CLASS_DELETED = "CLASS_DELETED";

// assessments
export const ASSESSMENTS_REQUESTED = "ASSESSMENTS_REQUESTED";
export const ASSESSMENTS_ERROR = "ASSESSMENTS_ERROR";
export const ASSESSMENT_CREATED = "ASSESSMENT_CREATED";
export const ASSESSMENTS_FETCHED = "ASSESSMENTS_FETCHED";
export const ASSESSMENT_RETURNED = "ASSESSMENT_RETURNED";
export const ASSESSMENT_COMPLETION_TOGGLED = "ASSESSMENT_COMPLETION_TOGGLED";
export const ASSESSMENT_UPDATED = "ASSESSMENT_UPDATED";
export const ASSESSMENT_DELETED = "ASSESSMENT_DELETED";

// tasks
export const TASKS_REQUESTED = "TASKS_REQUESTED";
export const TASKS_ERROR = "TASKS_ERROR";
export const TASK_CREATED = "TASK_CREATED";
export const TASKS_FETCHED = "TASKS_FETCHED";
export const TASK_RETURNED = "TASK_RETURNED";
export const TASK_COMPLETION_TOGGLED = "TASK_COMPLETION_TOGGLED";
export const TASK_UPDATED = "TASK_UPDATED";
export const TASK_DELETED = "TASK_DELETED";

// settings
export const SETTINGS_REQUESTED = "SETTINGS_REQUESTED";
export const SETTINGS_ERROR = "SETTINGS_ERROR";

export const PROFILE_RETURNED = "PROFILE_RETURNED";
export const PROFILE_UPDATED = "PROFILE_UPDATED";

export const PASSWORD_UPDATED = "PASSWORD_UPDATED";

export const PREFERENCES_RETURNED = "PREFERENCES_RETURNED";
export const PREFERENCES_UPDATED = "PREFERENCES_UPDATED";

// bugs
export const BUGS_REQUESTED = "BUGS_REQUESTED";
export const BUGS_ERROR = "BUGS_ERROR";
export const BUG_SUBMITTED = "BUG_SUBMITTED";

// feedback
export const FEEDBACK_REQUESTED = "FEEDBACK_REQUESTED";
export const FEEDBACK_ERROR = "FEEDBACK_ERROR";
export const FEEDBACK_SUBMITTED = "FEEDBACK_SUBMITTED";

// notifications
export const NOTIFICATIONS_REQUESTED = "NOTIFICATIONS_REQUESTED";
export const NOTIFICATIONS_ERROR = "NOTIFICATIONS_ERROR";
export const NOTIFICATION_CREATED = "NOTIFICATION_CREATED";
export const NOTIFATIONS_FETCHED = "NOTIFICATIONS_FETCHED";
export const NOTIFICATION_TOGGLED = "NOTIFICATION_TOGGLED";
export const NOTIFICATION_DELETED = "NOTIFICATION_DELETED";

/* --- PROPERTIES --- */
export const GEODATA_REQUESTED = "GEODATA_REQUESTED";
export const GEODATA_ERROR = "GEODATA_ERROR";
export const COUNTRIES_FETCHED = "COUNTRIES_FETCHED";
export const REGIONS_FETCHED = "REGIONS_FETCHED";
export const INSTITUTIONS_FETCHED = "INSTITUTIONS_FETCHED";
export const SCHOOLS_FETCHED = "SCHOOLS_FETCHED";

export const ACTIVE_TERM_REQUESTED = "ACTIVE_TERM_REQUESTED";
export const ACTIVE_TERM_FAILED = "ACTIVE_TERM_FAILED";
export const ACTIVE_TERM_SET = "ACTIVE_TERM_SET";

export const DEFAULT_PREFERENCE_REQUESTED = "DEFAULT_PREFERENCE_REQUESTED";
export const DEFAULT_PREFERENCE_ERROR = "DEFAULT_PREFERENCE_ERROR";
export const START_TIME_FETCHED = "START_TIME_FETCHED";
export const DEFAULT_DURATION_FETCHED = "DEFAULT_DURATION_FETCHED";
export const DEFAULT_CALENDAR_FETCHED = "DEFAULT_CALENDAR_FETCHED";
export const START_DAY_FETCHED = "START_DAY_FETCHED";