export const PROCESSING_FORM = "PROCESSING_FORM";
export const POST_INVITE = "POST_INVITE";
export const POST_CONTACT = "POST_CONTACT";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";